package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/suissa/UbiQUIC-eXtreme-zero-trust-message-queue/runtime/go/ubiq"
)

func main(){var listen,dbPath,defaultTransport,certFile,keyFile,caFile,trustFile string;var insecureDev,requireDPoP bool;flag.StringVar(&listen,"listen",":8443","HTTP/WS/SSE listen address");flag.StringVar(&dbPath,"db","data/ubiq-control.db","durable control-plane SQLite database");flag.StringVar(&defaultTransport,"transport","memory","default egress transport");flag.StringVar(&certFile,"tls-cert",os.Getenv("UBIQ_TLS_CERT"),"server certificate");flag.StringVar(&keyFile,"tls-key",os.Getenv("UBIQ_TLS_KEY"),"server private key");flag.StringVar(&caFile,"client-ca",os.Getenv("UBIQ_CLIENT_CA"),"CA used to require mTLS clients");flag.StringVar(&trustFile,"trust",os.Getenv("UBIQ_TRUST_FILE"),"JSON file with trusted UbiQ public bundles");flag.BoolVar(&insecureDev,"insecure-dev",false,"allow plaintext HTTP and transports for local development");flag.BoolVar(&requireDPoP,"require-dpop",envBool("UBIQ_REQUIRE_DPOP",true),"require RFC 9449 DPoP for HTTP mutations");flag.Parse();ctx,stop:=signal.NotifyContext(context.Background(),os.Interrupt,syscall.SIGTERM);defer stop();store,err:=ubiq.OpenControlStore(dbPath);must(err);defer store.Close();provider,err:=ubiq.NewCryptoProvider(envDefault("UBIQ_KEY_ID","ubiqd-local"));must(err);trust:=ubiq.NewStaticTrustStore();trust.Add(provider.Public());if trustFile!=""{must(loadTrust(trustFile,trust))};var serverTLS,clientTLS *tls.Config;if !insecureDev{if certFile==""||keyFile==""||caFile==""{log.Fatal("TLS certificate, key and client CA are required unless -insecure-dev is set")};serverTLS,clientTLS,err=tlsProfiles(certFile,keyFile,caFile);must(err)};registry:=ubiq.NewRegistry();defer registry.Close();add:=func(t ubiq.Transport){wrapped,err:=ubiq.WrapSecureTransport(t,provider,trust,2*time.Minute);must(err);must(registry.Register(wrapped))};add(ubiq.NewMemoryTransport("memory"));must(registerFromEnv(registry,add,serverTLS,clientTLS,insecureDev));api:=ubiq.NewServer(store,registry);api.DefaultTransport=defaultTransport;go api.RunMaintenance(ctx,time.Second);for _,name:=range registry.Names(){if name==defaultTransport{continue};if _,err:=api.BindTransport(ctx,name,"*");err!=nil{log.Printf("transport %s subscribe disabled: %v",name,err)}};handler:=api.Handler();if requireDPoP&&!insecureDev{handler=dpopMiddleware(ubiq.NewDPoPVerifier(),handler)};httpServer:=&http.Server{Addr:listen,Handler:handler,ReadHeaderTimeout:5*time.Second,IdleTimeout:60*time.Second,TLSConfig:serverTLS};errc:=make(chan error,1);go func(){if insecureDev{errc<-httpServer.ListenAndServe()}else{errc<-httpServer.ListenAndServeTLS(certFile,keyFile)}}();log.Printf("UbiQ listening on %s; transports=%v; default=%s",listen,registry.Names(),defaultTransport);select{case<-ctx.Done():shutdownCtx,cancel:=context.WithTimeout(context.Background(),5*time.Second);defer cancel();_=httpServer.Shutdown(shutdownCtx);case err:=<-errc:if !errors.Is(err,http.ErrServerClosed){log.Fatal(err)}}}

func registerFromEnv(_ *ubiq.Registry,add func(ubiq.Transport),serverTLS,clientTLS *tls.Config,insecure bool)error{if url:=os.Getenv("UBIQ_NATS_URL");url!=""{t,err:=ubiq.NewNATSTransport(ubiq.NATSConfig{Name:"nats",URL:url,Prefix:"ubiq"});if err!=nil{return err};add(t)};if url:=os.Getenv("UBIQ_JETSTREAM_URL");url!=""{t,err:=ubiq.NewNATSTransport(ubiq.NATSConfig{Name:"jetstream",URL:url,Prefix:"ubiq",JetStream:true,Stream:"UBIQ_EVENTS",DurablePrefix:"ubiq"});if err!=nil{return err};add(t)};if brokers:=csvEnv("UBIQ_KAFKA_BROKERS");len(brokers)>0{t,err:=ubiq.NewKafkaTransport(ubiq.KafkaConfig{Name:"kafka",Brokers:brokers,Topic:envDefault("UBIQ_KAFKA_TOPIC","ubiq-events")});if err!=nil{return err};add(t)};if brokers:=csvEnv("UBIQ_REDPANDA_BROKERS");len(brokers)>0{t,err:=ubiq.NewKafkaTransport(ubiq.KafkaConfig{Name:"redpanda",Brokers:brokers,Topic:envDefault("UBIQ_REDPANDA_TOPIC","ubiq-events")});if err!=nil{return err};add(t)};if url:=os.Getenv("UBIQ_RABBIT_URL");url!=""{t,err:=ubiq.NewRabbitTransport(ubiq.RabbitConfig{Name:"rabbitmq",URL:url,Exchange:"ubiq",QueuePrefix:"ubiq"});if err!=nil{return err};add(t)};if addr:=os.Getenv("UBIQ_REDIS_ADDR");addr!=""{add(ubiq.NewRedisStreamsTransport(ubiq.RedisStreamsConfig{Name:"redis-streams",Addr:addr,Stream:"ubiq-events",Group:"ubiq"}))};if broker:=os.Getenv("UBIQ_MQTT_BROKER");broker!=""{t,err:=ubiq.NewMQTTTransport(ubiq.MQTTConfig{Name:"mqtt",Broker:broker,ClientID:envDefault("UBIQ_MQTT_CLIENT_ID","ubiqd"),Prefix:"ubiq"});if err!=nil{return err};add(t)};if peer:=os.Getenv("UBIQ_TCP_PEER");peer!=""||os.Getenv("UBIQ_TCP_LISTEN")!=""{cfg:=ubiq.TCPConfig{Name:"tcp",PeerAddr:peer,ListenAddr:os.Getenv("UBIQ_TCP_LISTEN")};if !insecure{cfg.ClientTLS=clientTLS;cfg.ServerTLS=serverTLS};t,err:=ubiq.NewTCPTransport(cfg);if err!=nil{return err};add(t)};if peer:=os.Getenv("UBIQ_QUIC_PEER");peer!=""||os.Getenv("UBIQ_QUIC_LISTEN")!=""{if insecure{return errors.New("QUIC adapter requires TLS; insecure-dev cannot enable QUIC")};t,err:=ubiq.NewQUICTransport(ubiq.QUICConfig{Name:"quic",PeerAddr:peer,ListenAddr:os.Getenv("UBIQ_QUIC_LISTEN"),ClientTLS:cloneWithProto(clientTLS),ServerTLS:cloneWithProto(serverTLS)});if err!=nil{return err};add(t)};return nil}
func tlsProfiles(certFile,keyFile,caFile string)(*tls.Config,*tls.Config,error){cert,err:=tls.LoadX509KeyPair(certFile,keyFile);if err!=nil{return nil,nil,err};caRaw,err:=os.ReadFile(caFile);if err!=nil{return nil,nil,err};pool:=x509.NewCertPool();if !pool.AppendCertsFromPEM(caRaw){return nil,nil,errors.New("no CA certificate found")};server:=&tls.Config{MinVersion:tls.VersionTLS13,Certificates:[]tls.Certificate{cert},ClientCAs:pool,ClientAuth:tls.RequireAndVerifyClientCert};client:=&tls.Config{MinVersion:tls.VersionTLS13,Certificates:[]tls.Certificate{cert},RootCAs:pool};return server,client,nil}
func cloneWithProto(c *tls.Config)*tls.Config{if c==nil{return nil};x:=c.Clone();x.NextProtos=[]string{"ubiq/1"};return x}
func loadTrust(path string,store *ubiq.StaticTrustStore)error{raw,err:=os.ReadFile(path);if err!=nil{return err};var peers []ubiq.PublicBundle;if err:=json.Unmarshal(raw,&peers);err!=nil{return err};for _,p:=range peers{store.Add(p)};return nil}
func dpopMiddleware(verifier *ubiq.DPoPVerifier,next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if r.Method==http.MethodGet&&r.URL.Path=="/healthz"{next.ServeHTTP(w,r);return};proof:=r.Header.Get("DPoP");if proof==""{http.Error(w,"DPoP proof required",http.StatusUnauthorized);return};target:="https://"+r.Host+r.URL.Path;access:="";if auth:=r.Header.Get("Authorization");strings.HasPrefix(strings.ToLower(auth),"bearer "){access=strings.TrimSpace(auth[7:])};if err:=verifier.Verify(proof,r.Method,target,access,time.Now());err!=nil{http.Error(w,"invalid DPoP: "+err.Error(),http.StatusUnauthorized);return};next.ServeHTTP(w,r)})}
func csvEnv(k string)[]string{v:=strings.TrimSpace(os.Getenv(k));if v==""{return nil};parts:=strings.Split(v,",");out:=parts[:0];for _,p:=range parts{if p=strings.TrimSpace(p);p!=""{out=append(out,p)}};return out}
func envDefault(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
func envBool(k string,d bool)bool{v:=os.Getenv(k);if v==""{return d};b,err:=strconv.ParseBool(v);if err!=nil{return d};return b}
func must(err error){if err!=nil{log.Fatal(err)}}
var _=fmt.Sprintf
