package ubiq

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"sync"
	"time"
)

type MigrationState string
const (
	MigrationPlanned MigrationState="planned"; MigrationDualWrite MigrationState="dual_write"; MigrationBackfill MigrationState="backfill"; MigrationVerify MigrationState="verify"; MigrationCutover MigrationState="cutover"; MigrationComplete MigrationState="complete"; MigrationRolledBack MigrationState="rolled_back"
)
type ShardDocument struct{Key string;Data json.RawMessage}
type ShardBatch struct{Documents []ShardDocument;Next string;Done bool}
type ShardBackend interface{ID()string;ExportRange(context.Context,string,string,string,int)(ShardBatch,error);Import(context.Context,[]ShardDocument)error;CountRange(context.Context,string,string)(int64,error);DeleteRange(context.Context,string,string)error}
type ShardMigration struct{ID string `json:"id"`;Source string `json:"source"`;Destination string `json:"destination"`;RangeStart string `json:"range_start"`;RangeEnd string `json:"range_end"`;State MigrationState `json:"state"`;Checkpoint string `json:"checkpoint"`;UpdatedAtMS int64 `json:"updated_at_ms"`}
type ShardCoordinator struct{db *sql.DB;mu sync.RWMutex;backends map[string]ShardBackend}
func NewShardCoordinator(db *sql.DB)(*ShardCoordinator,error){c:=&ShardCoordinator{db:db,backends:make(map[string]ShardBackend)};_,err:=db.Exec(`CREATE TABLE IF NOT EXISTS shard_migrations(id TEXT PRIMARY KEY,source TEXT NOT NULL,destination TEXT NOT NULL,range_start TEXT NOT NULL,range_end TEXT NOT NULL,state TEXT NOT NULL,checkpoint TEXT NOT NULL DEFAULT '',updated_at_ms INTEGER NOT NULL);`);return c,err}
func(c *ShardCoordinator)Register(b ShardBackend)error{if b==nil||b.ID()==""{return errors.New("backend id required")};c.mu.Lock();defer c.mu.Unlock();if _,ok:=c.backends[b.ID()];ok{return fmt.Errorf("duplicate shard backend %q",b.ID())};c.backends[b.ID()]=b;return nil}
func(c *ShardCoordinator)backend(id string)(ShardBackend,error){c.mu.RLock();defer c.mu.RUnlock();b,ok:=c.backends[id];if !ok{return nil,fmt.Errorf("unknown shard backend %q",id)};return b,nil}
func(c *ShardCoordinator)Create(ctx context.Context,m ShardMigration)error{if m.ID==""||m.Source==""||m.Destination==""||m.Source==m.Destination{return errors.New("invalid migration")};if _,err:=c.backend(m.Source);err!=nil{return err};if _,err:=c.backend(m.Destination);err!=nil{return err};m.State=MigrationPlanned;m.UpdatedAtMS=time.Now().UnixMilli();_,err:=c.db.ExecContext(ctx,`INSERT INTO shard_migrations(id,source,destination,range_start,range_end,state,checkpoint,updated_at_ms) VALUES(?,?,?,?,?,?,?,?)`,m.ID,m.Source,m.Destination,m.RangeStart,m.RangeEnd,m.State,"",m.UpdatedAtMS);return err}
func(c *ShardCoordinator)Get(ctx context.Context,id string)(ShardMigration,error){var m ShardMigration;err:=c.db.QueryRowContext(ctx,`SELECT id,source,destination,range_start,range_end,state,checkpoint,updated_at_ms FROM shard_migrations WHERE id=?`,id).Scan(&m.ID,&m.Source,&m.Destination,&m.RangeStart,&m.RangeEnd,&m.State,&m.Checkpoint,&m.UpdatedAtMS);return m,err}
func(c *ShardCoordinator)setState(ctx context.Context,id string,from []MigrationState,to MigrationState,checkpoint string)error{args:=[]any{to,checkpoint,time.Now().UnixMilli(),id};marks:="";for i,s:=range from{if i>0{marks+=","};marks+="?";args=append(args,s)};q:=fmt.Sprintf(`UPDATE shard_migrations SET state=?,checkpoint=?,updated_at_ms=? WHERE id=? AND state IN (%s)`,marks);res,err:=c.db.ExecContext(ctx,q,args...);if err!=nil{return err};n,_:=res.RowsAffected();if n!=1{return errors.New("invalid migration transition")};return nil}
func(c *ShardCoordinator)EnableDualWrite(ctx context.Context,id string)error{return c.setState(ctx,id,[]MigrationState{MigrationPlanned},MigrationDualWrite,"")}
func(c *ShardCoordinator)BeginBackfill(ctx context.Context,id string)error{return c.setState(ctx,id,[]MigrationState{MigrationDualWrite},MigrationBackfill,"")}
func(c *ShardCoordinator)BackfillStep(ctx context.Context,id string,limit int)(bool,error){if limit<=0{limit=500};m,err:=c.Get(ctx,id);if err!=nil{return false,err};if m.State!=MigrationBackfill{return false,errors.New("migration is not in backfill")};src,err:=c.backend(m.Source);if err!=nil{return false,err};dst,err:=c.backend(m.Destination);if err!=nil{return false,err};batch,err:=src.ExportRange(ctx,m.RangeStart,m.RangeEnd,m.Checkpoint,limit);if err!=nil{return false,err};if len(batch.Documents)>0{if err:=dst.Import(ctx,batch.Documents);err!=nil{return false,err}};if batch.Done{if err:=c.setState(ctx,id,[]MigrationState{MigrationBackfill},MigrationVerify,batch.Next);err!=nil{return false,err};return true,nil};_,err=c.db.ExecContext(ctx,`UPDATE shard_migrations SET checkpoint=?,updated_at_ms=? WHERE id=? AND state=?`,batch.Next,time.Now().UnixMilli(),id,MigrationBackfill);return false,err}
func(c *ShardCoordinator)Verify(ctx context.Context,id string)error{m,err:=c.Get(ctx,id);if err!=nil{return err};if m.State!=MigrationVerify{return errors.New("migration is not ready to verify")};src,err:=c.backend(m.Source);if err!=nil{return err};dst,err:=c.backend(m.Destination);if err!=nil{return err};a,err:=src.CountRange(ctx,m.RangeStart,m.RangeEnd);if err!=nil{return err};b,err:=dst.CountRange(ctx,m.RangeStart,m.RangeEnd);if err!=nil{return err};if a!=b{return fmt.Errorf("verification failed: source=%d destination=%d",a,b)};return c.setState(ctx,id,[]MigrationState{MigrationVerify},MigrationCutover,m.Checkpoint)}
func(c *ShardCoordinator)Complete(ctx context.Context,id string,deleteSource bool)error{m,err:=c.Get(ctx,id);if err!=nil{return err};if m.State!=MigrationCutover{return errors.New("migration is not cut over")};if deleteSource{src,err:=c.backend(m.Source);if err!=nil{return err};if err:=src.DeleteRange(ctx,m.RangeStart,m.RangeEnd);err!=nil{return err}};return c.setState(ctx,id,[]MigrationState{MigrationCutover},MigrationComplete,m.Checkpoint)}
func(c *ShardCoordinator)Rollback(ctx context.Context,id string)error{m,err:=c.Get(ctx,id);if err!=nil{return err};if m.State==MigrationCutover||m.State==MigrationComplete{return errors.New("cannot rollback after cutover")};dst,err:=c.backend(m.Destination);if err!=nil{return err};if err:=dst.DeleteRange(ctx,m.RangeStart,m.RangeEnd);err!=nil{return err};return c.setState(ctx,id,[]MigrationState{MigrationPlanned,MigrationDualWrite,MigrationBackfill,MigrationVerify},MigrationRolledBack,m.Checkpoint)}
func(c *ShardCoordinator)TargetsForWrite(ctx context.Context,key string)([]string,error){rows,err:=c.db.QueryContext(ctx,`SELECT source,destination,state,range_start,range_end FROM shard_migrations WHERE state != ?`,MigrationRolledBack);if err!=nil{return nil,err};defer rows.Close();set:=map[string]struct{}{};for rows.Next(){var src,dst,start,end string;var state MigrationState;if err:=rows.Scan(&src,&dst,&state,&start,&end);err!=nil{return nil,err};if key<start||key>=end{continue};switch state{case MigrationPlanned:set[src]=struct{}{};case MigrationDualWrite,MigrationBackfill,MigrationVerify:set[src]=struct{}{};set[dst]=struct{}{};case MigrationCutover,MigrationComplete:set[dst]=struct{}{}}};out:=make([]string,0,len(set));for id:=range set{out=append(out,id)};sort.Strings(out);return out,rows.Err()}
